version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: f1_strategy_db
    environment:
      POSTGRES_USER: f1_analyst
      POSTGRES_PASSWORD: f1_strategy_2025
      POSTGRES_DB: f1_strategy
    ports:
      -"5432:5432"
    volumes:
      -postgres_data:/var/lib/postgresql/data
      ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - f1_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: f1_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@f1strategy.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - f1_network

volumes:
  postgres_data:

networks:
  f1_network:
    driver: bridge