-- were following a clean state protocol here. so in order to do that, first we need to clear anything in the database similar to what were gonna add later.
-- So were going to Drop tables if they exist
